pipeline:

  build_image:
    image: quay.io/ukhomeofficedigital/centos-base:latest
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - yum install -y -q docker openssl wget
      - ./ci-build.sh
    when:
      event: [pull_request, push, tag]

  push_image:
    image: docker:1.11
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
      - DOCKER_IMAGE=nginx-proxy
      - DOCKER_REPO=artifactory-internal.digital.homeoffice.gov.uk
      - DOCKER_BASEDIR=/
      - DOCKER_USERNAME=lev-web-robot
    commands:
      - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}" "${DOCKER_REPO}"
      - ./publish.sh "ngx" "${DOCKER_REPO}${DOCKER_BASEDIR}${DOCKER_IMAGE}" "${DRONE_TAG}"
    when:
      event: tag

  push_image_to_quay:
    image: docker:1.11
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
      - DOCKER_IMAGE=nginx-proxy
      - DOCKER_REPO=quay.io
      - DOCKER_BASEDIR=/ukhomeofficedigital/
      - DOCKER_USERNAME=ukhomeofficedigital+nginx_proxy
    commands:
      - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_QUAY_PASSWORD}" "${DOCKER_REPO}"
      - ./publish.sh "ngx" "${DOCKER_REPO}${DOCKER_BASEDIR}${DOCKER_IMAGE}" "${DRONE_TAG}"
    when:
      event: tag

services:
  dind:
    image: docker:1.13-dind
    privileged: true
    command:
      - "-s"
      - "overlay"
